version: "3.8"

services:
  postgres:
    build:
      context: ./local-aws-extensions
      dockerfile: Dockerfile
    restart: always
    ports: ["5432:5432"]
    expose: ["5432"]
    volumes:
      - ./.volumes/postgres:/var/lib/postgresql/data
      - ./local-aws-extensions/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: mydb
  flyway:
    image: flyway/flyway:latest
    command: -configFiles=/flyway/conf/flyway.config -locations=filesystem:/flyway/sql -connectRetries=60 migrate
    volumes:
      - ${PWD}/sql:/flyway/sql
      - ${PWD}/flyway.config:/flyway/conf/flyway.config
    depends_on:
      - postgres
